name: Container Docker
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest # we would run a job inside a docker container in the virtual machine
    container:
      image: node:13.5.0-alpine3.10
      #optinos: --cpus # define restrictions for the container
      #volumes:  # we can map volumes to the container
    steps:
      - name: Log node node-version
        run: |     # Display current version and os of our docker 
          node -v   
          cat /etc/os-release