name: notify last step result
on:
   workflow_dispatch:
     

jobs:
   notifystepresult:
      runs-on: ubuntu-20.04
      # continue-on-error=true this would force to continue other steps no matter the previos step have failed
      steps:
      - name: step output capture
        id: maven-deploy
        run: |
         mvn deploy| grep 'ERROR' | tee mvnrst.log
         echo "::set-output name=mvndeployrst::$(cat mvnrst.log)"
      #result_code=${PIPESTATUS[0]}
      #exit $result_code
      - name: Notify about failure if last step failed
        env:
          check: ${{ contains(steps.maven-deploy.outputs.mvndeployrst, 'ERROR') }} 
        run: |
          echo "THE RESULT FROM CHECK IS"
          echo ${check}
          echo "THIS IS THE RESULT FROM LAST STEP TO NOTIFY"
          cat ${{ steps.maven-deploy.outputs.mvndeployrst }}
      - name: Notify about other failure
        if: ${{ failure() }}
        run: |
          echo "THIS IS THE NORMAL FAILURE"

#      work:
#       needs: check
#       if: !contains(needs.check.outputs.status, 'failure')
#       steps:
#        - run: foo
#        - run: ...



 #     - name: Install dependencies
 #       id: composer-run
 #       continue-on-error: true
 #       run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

 #     - name: Execute tests
 #       if: steps.composer-run.outcome == 'success' && steps.composer-run.conclusion == 'success'
 #       run: vendor/bin/phpunit