name: Generate random failure
on: workflow_dispatch
jobs:
  randomly-failing-job:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - name: Generate 0 or 1
        id: generate_number
        run:  echo "::set-output name=random_number::$(($RANDOM % 2))"
      - name: Pass or fail
        run: |
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; 
           then 
              echo "notify it was success"
              exit 0; 
          else 
              echo "notify it fail"
              exit 1; 
          fi