name: Container Docker
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo" # To override the entry point of a docker container
          args: "Hello from Docker Inside Step"
      - name: Node Log Version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/usr/local/bin/node" # To pass wntry point we have to check the complete path of executable with type -a command
          args: "-v"
      - uses: actions/checkout@v1  # We checkout the script to be able to use it in the workflow
      - name: Run personal script
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "./dockerscript.sh" # To pass wntry point we have to check the complete path of executable with type -a command
          args: "hi google"
      - name: Send a Slack Notification to a Channel   # In order to interact with slack channel we must create an app app.slack.com/app, configure for workspace and channel
        if: failure()
        uses: docker://technosophos/slack-notify
        env:  # The webhook needs to be configured by secret because if not slack would block it and send an email about the expose of your secret to write to channel
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}  # webhook copied from slack application, after authorizing the webhook to a slack channel
          SLACK_MESSAGE: "Publishing something to slack channel from github actions"
  node-docker:
    runs-on: ubuntu-latest # we would run a job inside a docker container in the virtual machine
    container:
      image: node:13.5.0-alpine3.10
      #optinos: --cpus # define restrictions for the container
      #volumes:  # we can map volumes to the container
    steps:
      - name: Log node node-version
        run: |     # Display current version and os of our docker 
          node -v   
          cat /etc/os-release